### ISSUE TITLE
Is it possible to have multiple targets for an SRV record?

### ISSUE THREAD

**Issue by joshrosso** [sky-uk/terraform-provider-infoblox#68]
Any ways to do multiple targets on an srv record: https://github.com/sky-uk/terraform-provider-infoblox/blob/master/infoblox/resource_srv_record.go#L30-L33

Basically I have 3 CNAMEs I'd like to associate with an SRV. All are on the same port.

**Comment by craig-duffin** [comment]
Hi, unfortunately Infoblox does not allow you to define multiple targets from an SRV record. You would have to define a SRV record for each target.

**Comment by joshrosso** [comment]
Thanks @craig-duffin. 

I may have misunderstood how infoblox handles SRV records. Seems, as you suggested, I can add multiple srv records with the same name, each containing unique targets.
