### ISSUE TITLE
unexpected EOF on terraform apply : panic: interface conversion: interface {} is nil, not []interface {}

### ISSUE THREAD

**Issue by Priteshkal** [sky-uk/terraform-provider-infoblox#83]
### Terraform Version
Terraform v0.11.8
+ provider.infoblox v0.1.11

### main.tf 
```
provider "infoblox" {
  username             = "${var.infoblox_username}"
  password             = "${var.infoblox_password}"
  server               = "${var.infoblox_server}"
  allow_unverified_ssl = "${var.infoblox_sslverify}"
  version              = "0.1.11"
}
resource "infoblox_arecord" "acctest" {
  name     = "hello.local"
  ipv4addr = "10.0.0.10"
  ttl      = 9000
}
```

### Crash.log
[crash.log](https://github.com/sky-uk/terraform-provider-infoblox/files/2316079/crash.log)

**Comment by keithhopkins-gpc** [comment]
Try setting the WAPI version in the provider.  Our Infobox is only v2.5, but the current code defaults to v2.6.1, and that caused this type of error.

**Comment by Priteshkal** [comment]
That does it. Thank you @keithhopkins-gpc
