### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by jimrazmus** [sky-uk/terraform-provider-infoblox#86]
It does not appear to be so.

**Comment by grubert65** [comment]
Sorry, the project is not maintained anymore by it's creators.
-Marco.

Il giorno mer 23 gen 2019 alle ore 15:29 Jim Razmus II <
notifications@github.com> ha scritto:

**Comment by jasonmcintosh** [comment]
Released a new version which added extattrs support.  https://github.com/CARFAX/terraform-provider-infoblox for source.

**Comment by pgrinstead1** [comment]
@jasonmcintosh does your module support 0.12.X?
-Paul

**Comment by jasonmcintosh** [comment]
It was built pretty recently but can't recall if I updated it to support the latest plugin versions (aka to support 0.12.x).  Shouldn't be TOO hard to do so if not been done.  Note, I'm no longer at Carfax, and thus unable to maintain it directly...  you can post an issue there try get someone to try it with 0.12.x.

**Comment by pgrinstead1** [comment]
Thank you @jasonmcintosh, I appreciate the speedy response.

**Comment by tomasaberg** [comment]
@jasonmcintosh Will you support `import`?

**Comment by jimrazmus** [comment]
Closing this issue.
